#!/usr/bin/python

import commands, os

sourceFile = "usr/lib/linuxmint/mintDrivers/mintDrivers.py"

menuName = commands.getoutput("cat " + sourceFile + " | grep menuName")
menuName = menuName.replace("menuName", "")
menuName = menuName.replace("=", "")
menuName = menuName.replace("_(", "")
menuName = menuName.replace("\"", "")
menuName = menuName.replace(")", "")
menuName = menuName.strip()

menuComment = commands.getoutput("cat " + sourceFile + " | grep menuComment")
menuComment = menuComment.replace("menuComment", "")
menuComment = menuComment.replace("=", "")
menuComment = menuComment.replace("_(", "")
menuComment = menuComment.replace("\"", "")
menuComment = menuComment.replace(")", "")
menuComment = menuComment.strip()

desktopFile = open("usr/share/applications/mintdrivers.desktop", "w")
desktopFile.writelines("""[Desktop Entry]
Name=Driver Manager
""")

import gettext
gettext.install("mintdrivers", "/usr/share/linuxmint/locale")

for directory in os.listdir("/usr/share/linuxmint/locale"):
	if os.path.isdir(os.path.join("/usr/share/linuxmint/locale", directory)):
		try:
			language = gettext.translation('mintdrivers', "/usr/share/linuxmint/locale", languages=[directory])
			language.install()
			desktopFile.writelines("Name[%s]=%s\n" % (directory, _(menuName)))
		except:
			pass

desktopFile.writelines("Comment=Manage the drivers for your devices\n")

for directory in os.listdir("/usr/share/linuxmint/locale"):
	if os.path.isdir(os.path.join("/usr/share/linuxmint/locale", directory)):
		try:
			language = gettext.translation('mintdrivers', "/usr/share/linuxmint/locale", languages=[directory])
			language.install()			
			desktopFile.writelines("Comment[%s]=%s\n" % (directory, _(menuComment)))
		except:
			pass

desktopFile.writelines("""Exec=driver-manager
Icon=jockey
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=GNOME;GTK;Settings;X-GNOME-SystemSettings;X-GNOME-Settings-Panel;
X-GNOME-Settings-Panel=driver-manager
X-KDE-SubstituteUID=true
X-Ubuntu-Gettext-Domain=mintdrivers
""")

