#!/usr/bin/python

DOMAIN = "mintdrivers"
PATH = "/usr/share/linuxmint/locale"

import os, gettext, sys
sys.path.append('/usr/lib/linuxmint/common')
import additionalfiles

os.environ['LANG'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=driver-manager
Icon=mintdrivers
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=GNOME;GTK;System;Settings;X-GNOME-SystemSettings;X-GNOME-Settings-Panel;XFCE;X-XFCE-SettingsDialog;X-XFCE-SystemSettings;
X-GNOME-Settings-Panel=driver-manager
X-KDE-SubstituteUID=true
NotShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/mintdrivers.desktop", prefix, _("Driver Manager"), _("Manage the drivers for your devices"), suffix)


prefix = "[Desktop Entry]\n"

suffix= """Exec=driver-manager
NoDisplay=true
Icon=/usr/share/icons/hicolor/scalable/apps/driver-manager.svg
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Qt;KDE;System;
X-KDE-StartupNotify=false
OnlyShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/kde4/mintdrivers.desktop", prefix, _("Driver Manager"), _("Manage the drivers for your devices"),  suffix, genericName=_("Manage the drivers for your devices"))

